# 开发配置
"""
Django settings for lufyy_api project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL, MEDIA_URL, MEDIA_ROOT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qals5hm5#9wuod71+@c7351_%6bxfl#vp4rdfgwhidfn4ttrp2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

import sys,os
# 获取 lufyy_api 目录
lufyy_api_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 获取 apps 目录
apps_dir = os.path.join(lufyy_api_dir, 'apps')
# 添加到 Python 路径
sys.path.insert(0, apps_dir)

# 另外一种方法
    # from pathlib import Path
    # lufyy_api_dir = Path(__file__).resolve().parent.parent
    # apps_dir = os.path.join(lufyy_api_dir, 'apps')
    # sys.path.insert(0, apps_dir)


INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin', # 后台管理
    'django.contrib.auth',  #auth 权限表
    'django.contrib.contenttypes', # 记录了所有内置或者你写的app表
    'django.contrib.sessions', # 咱们用的session，django-session表
    'django.contrib.messages', # 消息框架
    'django.contrib.staticfiles', # 静态文件
    'rest_framework',
    'user',
    'home'
]

# 设置simpleui的主题
# 指定simpleui默认的主题,指定一个文件名，相对路径就从simpleui的theme目录读取
SIMPLEUI_DEFAULT_THEME = 'ant.design'

# 导入cors自定义中间价
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # 安全中间件 用户认证
    'django.contrib.sessions.middleware.SessionMiddleware', # session相关
    'django.middleware.common.CommonMiddleware',# 公用的一些工具，例如common的
    'django.middleware.csrf.CsrfViewMiddleware',# csrf相关
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 认证相关
    'django.contrib.messages.middleware.MessageMiddleware', # 消息框架
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # xFrame相关的
    'utils.common_middleware.CorsMiddleware'
]

ROOT_URLCONF = 'lufyy_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'lufyy_api/../../templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lufyy_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "luffy",
        "USER": "dev",
        "PASSWORD": "devdev123123",
        "HOST": "www.tgthink.cn",
        "PORT": "33306",
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


AUTH_USER_MODEL='user.user'



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True

# 国际化
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 所有表，id字段默认使用bigautofield
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            # 实际开发建议使用WARNING
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            # 实际开发建议使用ERROR
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            # 日志位置,日志文件名,日志保存目录必须手动创建，注：这里的文件路径要注意BASE_DIR代表的是小luffyapi
            'filename': os.path.join(os.path.dirname(BASE_DIR), "logs", "luffy.log"),
            # 日志文件的最大值,这里我们设置300M
            'maxBytes': 300 * 1024 * 1024,
            # 日志文件的数量,设置最大日志数量为10
            'backupCount': 10,
            # 日志格式:详细格式
            'formatter': 'verbose',
            # 文件内容编码
            'encoding': 'utf-8'
        },
    },
    # 日志对象
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'propagate': True,  # 是否让日志信息继续冒泡给其他的日志处理系统
        },
    }
}

# 封装全局异常
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'utils.custom_exception.GlobalException',
}


# 开放访问图片
MEDIA_URL='/media/' # http://127.0.0.1:8080/media/icon/default.png
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# LU_ROOT = os.path.join(os.path.dirname(BASE_DIR),'logs') # 测试


import time
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['首页功能','权限认证', '测试demo'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'name': '首页功能',
        'icon': 'fas fa-code',
        'models':[{
            'name': '轮播图管理',
            'icon': 'fas fa-carousel',
            'url': 'home/bannermodel/'
        }],
        # 浏览器新标签中打开
        'newTab': True,
    }, {
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '组管理',
            'icon': 'fa fa-user-group',
            'url': 'auth/group/'
        },
        {
            'name': '权限管理',
            'icon': 'fas fa-key',
            'url': 'auth/permission/'
        },
        {
            'name': '用户管理',
            'icon': 'fa fa-user',
            'url': 'user/user/'
        },
        ]
    },
        {
        'name': '测试demo',
        'icon': 'fa fa-desktop',
        'url': '/demo/',  # 加上末尾斜杠
    }]
}