# Generated by Django 4.2.17 on 2026-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_showed', models.BooleanField(default=True, verbose_name='是否上架')),
                ('orders', models.IntegerField(verbose_name='优先级')),
                ('title', models.CharField(max_length=16, unique=True, verbose_name='名称')),
                ('image', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('link', models.CharField(max_length=64, verbose_name='跳转链接')),
                ('info', models.TextField(verbose_name='详情')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'luffy_banner',
            },
        ),
    ]
